// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinDex.Api.Data;

#nullable disable

namespace VinDex.Api.Migrations
{
    [DbContext(typeof(VinDexDbContext))]
    [Migration("20260206213829_UpdatedDb")]
    partial class UpdatedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinDex.Api.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abs")
                        .HasColumnType("text");

                    b.Property<string>("AdaptiveCruiseControl")
                        .HasColumnType("text");

                    b.Property<string>("AirBagCurtain")
                        .HasColumnType("text");

                    b.Property<string>("AirBagFront")
                        .HasColumnType("text");

                    b.Property<string>("AirBagSide")
                        .HasColumnType("text");

                    b.Property<string>("AutomaticPedestrianAlertingSound")
                        .HasColumnType("text");

                    b.Property<string>("Axles")
                        .HasColumnType("text");

                    b.Property<string>("BlindSpotIntervention")
                        .HasColumnType("text");

                    b.Property<string>("BlindSpotMonitoring")
                        .HasColumnType("text");

                    b.Property<string>("BodyStyle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurbWeight")
                        .HasColumnType("text");

                    b.Property<string>("DaytimeRunningLights")
                        .HasColumnType("text");

                    b.Property<double?>("DisplacementLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("Doors")
                        .HasColumnType("text");

                    b.Property<string>("DriveType")
                        .HasColumnType("text");

                    b.Property<int?>("EngineCylinders")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text");

                    b.Property<string>("Esc")
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<string>("Gvwr")
                        .HasColumnType("text");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<string>("KeylessIgnition")
                        .HasColumnType("text");

                    b.Property<string>("LaneDepartureWarning")
                        .HasColumnType("text");

                    b.Property<string>("LaneKeepSystem")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParkAssist")
                        .HasColumnType("text");

                    b.Property<string>("PlantCity")
                        .HasColumnType("text");

                    b.Property<string>("PlantCompanyName")
                        .HasColumnType("text");

                    b.Property<string>("PlantCountry")
                        .HasColumnType("text");

                    b.Property<string>("PlantState")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("TopSpeedMph")
                        .HasColumnType("text");

                    b.Property<string>("Tpms")
                        .HasColumnType("text");

                    b.Property<string>("TransmissionStyle")
                        .HasColumnType("text");

                    b.Property<string>("Trim")
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WheelBase")
                        .HasColumnType("text");

                    b.Property<string>("WheelSizeFront")
                        .HasColumnType("text");

                    b.Property<string>("WheelSizeRear")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
